package com.quietus.util;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated by Deep Seek */
public class MapUtil {
    public static <K, V> void moveEntryToFirst(LinkedHashMap<K, V> map, int n) {
        if (map == null || n < 0 || n >= map.size()) {
            return; // or throw IllegalArgumentException
        }

        // Get all entries as a list
        List<Map.Entry<K, V>> entries = new ArrayList<>(map.entrySet());

        // Target entry
        Map.Entry<K, V> target = entries.get(n);

        // Build a new LinkedHashMap with the desired order
        LinkedHashMap<K, V> newMap = new LinkedHashMap<>();
        // Insert the target first
        newMap.put(target.getKey(), target.getValue());
        // Insert the rest in original order, skipping the target
        for (int i = 0; i < entries.size(); i++) {
            if (i == n) continue;
            Map.Entry<K, V> e = entries.get(i);
            newMap.put(e.getKey(), e.getValue());
        }

        // Clear original map and put all entries from newMap
        map.clear();
        map.putAll(newMap);
    }

    public static <K, V> void moveEntryToFirst(LinkedHashMap<K, V> map, K key) {
        if (map == null) {
            throw new IllegalArgumentException("Map cannot be null");
        }
        if (!map.containsKey(key)) {
            throw new IllegalArgumentException("Key not found in map: " + key);
        }

        // If it's already first, nothing to do
        K firstKey = map.keySet().iterator().next();
        if (Objects.equals(firstKey, key)) {
            return;
        }

        // Build a new map with the target entry first, then all others in original order
        LinkedHashMap<K, V> newMap = new LinkedHashMap<>();
        
        // First, put the target entry
        V value = map.get(key);
        newMap.put(key, value);
        
        // Then put all other entries, skipping the target
        for (Map.Entry<K, V> entry : map.entrySet()) {
            K currentKey = entry.getKey();
            if (!Objects.equals(currentKey, key)) {
                newMap.put(currentKey, entry.getValue());
            }
        }

        // Replace contents of original map
        map.clear();
        map.putAll(newMap);
    }
}