package com.quietus.data;

import com.quietus.block.QuietusBlocks;
import com.quietus.data.ItemModelProperties.GrapplingHookCast;
import com.quietus.item.QuietusItems;
import com.quietus.item.equipment.QuietusArmorMaterials;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.client.data.models.model.*;
import net.minecraft.client.renderer.block.model.BlockStateModelWrapper;
import net.minecraft.client.renderer.item.*;
import net.minecraft.client.renderer.item.properties.numeric.UseDuration;
import net.minecraft.client.renderer.item.properties.select.DisplayContext;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.Identifier;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemDisplayContext;
import net.minecraft.world.level.block.Block;
import org.jspecify.annotations.NonNull;

import java.util.stream.Stream;

import static com.quietus.Quietus.MODID;

public class QuietusModelProvider extends ModelProvider {
    public QuietusModelProvider(PackOutput output) {
        super(output, MODID);
    }

    //From Now on, we are no longer having the "items" folder in the mod assets, as they should be generated by datagen.
    // EVERY ITEM OR BLOCK CREATED MUST BE ADDED HERE, use the RegisterBasicModel method if you have customized model json in quietus:models in mod assets.
    // Do a Data run with the mod to update the generation of assets
    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels)
    {
       //flat items
        //RegisterBasicModel(itemModels,QuietusItems.HARDENED_FUR.get(),"item/ingredients/");
        itemModels.itemModelOutput.accept(QuietusItems.HARDENED_FUR.get(),ItemModelUtils.plainModel(Identifier.fromNamespaceAndPath(MODID,"item/ingredients/hardened_fur")));
        itemModels.generateFlatItem(QuietusItems.EXAMPLE_ITEM.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(QuietusItems.MOLD.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(QuietusItems.MOLD_BOWL.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(QuietusItems.MOLD_BUCKET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(QuietusItems.YOGHURT_BUCKET.get(), ModelTemplates.FLAT_ITEM);
        itemModels.generateFlatItem(QuietusItems.CHEESE_BUCKET.get(), ModelTemplates.FLAT_ITEM);

    //handheld
        itemModels.itemModelOutput.accept(QuietusItems.AMETHYST_STAFF.get(),ItemModelUtils.plainModel(Identifier.fromNamespaceAndPath(MODID,"item/combat/magic_weapon/amethyst_staff")));
        itemModels.generateFlatItem(QuietusItems.WEIRD_AMETHYST_STAFF.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        //RegisterBasicModel(itemModels,QuietusItems.CHAIN_GRAPPLING_HOOK.get(),"item/tools/grapples/");

    //chain hook 2d 3d simultaneous rendering
        Item myItem = QuietusItems.CHAIN_GRAPPLING_HOOK.get();
        var unbaked2d = ItemModelUtils.plainModel(Identifier.fromNamespaceAndPath(MODID,"item/tools/grapples/chain_grappling_hook_2d"));
        var unbaked3d = ItemModelUtils.plainModel(Identifier.fromNamespaceAndPath(MODID,"item/tools/grapples/chain_grappling_hook_3d"));
        var unbakedCast = ItemModelUtils.plainModel(Identifier.fromNamespaceAndPath(MODID,"item/tools/grapples/chain_grappling_hook_cast"));

        // The property that checks for the marker component
        var castProperty = new GrapplingHookCast();
        // Build the select model with cases for each display context
        var selectModel = ItemModelUtils.select(
               new DisplayContext(),                     // property: minecraft:display_context
                unbaked2d,                                    // fallback model
                // GUI contexts -> 2D
                ItemModelUtils.when(ItemDisplayContext.GUI, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked2d)),
                ItemModelUtils.when(ItemDisplayContext.FIXED, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked2d)),
                // Hand contexts -> 3D
                ItemModelUtils.when(ItemDisplayContext.FIRST_PERSON_LEFT_HAND, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked3d)),
                ItemModelUtils.when(ItemDisplayContext.FIRST_PERSON_RIGHT_HAND, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked3d)),
                ItemModelUtils.when(ItemDisplayContext.THIRD_PERSON_LEFT_HAND, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked3d)),
                ItemModelUtils.when(ItemDisplayContext.THIRD_PERSON_RIGHT_HAND, ItemModelUtils.conditional(castProperty, unbakedCast, unbaked3d)),
                ItemModelUtils.when(ItemDisplayContext.GROUND, unbaked3d)
        );
        itemModels.itemModelOutput.accept(myItem,selectModel);


        //copper tools
        itemModels.generateFlatItem(QuietusItems.EXPOSED_COPPER_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.WEATHERED_COPPER_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.OXIDIZED_COPPER_AXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(QuietusItems.EXPOSED_COPPER_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.WEATHERED_COPPER_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.OXIDIZED_COPPER_HOE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(QuietusItems.EXPOSED_COPPER_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.WEATHERED_COPPER_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.OXIDIZED_COPPER_PICKAXE.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(QuietusItems.EXPOSED_COPPER_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.WEATHERED_COPPER_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.OXIDIZED_COPPER_SHOVEL.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        itemModels.generateFlatItem(QuietusItems.EXPOSED_COPPER_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.WEATHERED_COPPER_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);
        itemModels.generateFlatItem(QuietusItems.OXIDIZED_COPPER_SWORD.get(), ModelTemplates.FLAT_HANDHELD_ITEM);

        //bows
        RegisterBow(itemModels,QuietusItems.TRIPLEBOW.get(),"item/combat/");

        //itemModels.createFlatItemModel(QuietusItems.TRIPLEBOW.get(), ModelTemplates.BOW);
        //itemModels.generateBow(QuietusItems.TRIPLEBOW.get());

        itemModels.createFlatItemModel(QuietusItems.INFINIBOW.get(), ModelTemplates.BOW);
        itemModels.generateBow(QuietusItems.INFINIBOW.get());

        itemModels.createFlatItemModel(QuietusItems.PULLBOW.get(), ModelTemplates.BOW);
        itemModels.generateBow(QuietusItems.PULLBOW.get());

        itemModels.createFlatItemModel(QuietusItems.INSTABOW.get(), ModelTemplates.BOW);
        itemModels.generateBow(QuietusItems.INSTABOW.get());


        //trimmables

        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_COPPER_HELMET.get(), QuietusArmorMaterials.EXPOSED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_COPPER_CHESTPLATE.get(), QuietusArmorMaterials.EXPOSED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_COPPER_LEGGINGS.get(), QuietusArmorMaterials.EXPOSED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_COPPER_BOOTS.get(), QuietusArmorMaterials.EXPOSED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_COPPER_HELMET.get(), QuietusArmorMaterials.WEATHERED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_COPPER_CHESTPLATE.get(), QuietusArmorMaterials.WEATHERED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_COPPER_LEGGINGS.get(), QuietusArmorMaterials.WEATHERED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_COPPER_BOOTS.get(), QuietusArmorMaterials.WEATHERED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_COPPER_HELMET.get(), QuietusArmorMaterials.OXIDIZED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_COPPER_CHESTPLATE.get(), QuietusArmorMaterials.OXIDIZED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_COPPER_LEGGINGS.get(), QuietusArmorMaterials.OXIDIZED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_COPPER_BOOTS.get(), QuietusArmorMaterials.OXIDIZED_COPPER_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_IRON_HELMET.get(), QuietusArmorMaterials.EXPOSED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_IRON_CHESTPLATE.get(), QuietusArmorMaterials.EXPOSED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_IRON_LEGGINGS.get(), QuietusArmorMaterials.EXPOSED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.EXPOSED_IRON_BOOTS.get(), QuietusArmorMaterials.EXPOSED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_IRON_HELMET.get(), QuietusArmorMaterials.WEATHERED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_IRON_CHESTPLATE.get(), QuietusArmorMaterials.WEATHERED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_IRON_LEGGINGS.get(), QuietusArmorMaterials.WEATHERED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.WEATHERED_IRON_BOOTS.get(), QuietusArmorMaterials.WEATHERED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_IRON_HELMET.get(), QuietusArmorMaterials.OXIDIZED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_IRON_CHESTPLATE.get(), QuietusArmorMaterials.OXIDIZED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_IRON_LEGGINGS.get(), QuietusArmorMaterials.OXIDIZED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.OXIDIZED_IRON_BOOTS.get(), QuietusArmorMaterials.OXIDIZED_IRON_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        itemModels.generateTrimmableItem(QuietusItems.AMETHYST_HELMET.get(), QuietusArmorMaterials.AMETHYST_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/helmet_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.AMETHYST_CHESTPLATE.get(), QuietusArmorMaterials.AMETHYST_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/chestplate_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.AMETHYST_LEGGINGS.get(), QuietusArmorMaterials.AMETHYST_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/leggings_trim"), false);
        itemModels.generateTrimmableItem(QuietusItems.AMETHYST_BOOTS.get(), QuietusArmorMaterials.AMETHYST_KEY, Identifier.fromNamespaceAndPath("minecraft", "trims/items/boots_trim"),  false);

        //System.out.println(ModelLocationUtils.getModelLocation(QuietusItems.EXPOSED_COPPER_BOOTS.get()) != null ? ModelLocationUtils.getModelLocation(QuietusItems.EXPOSED_COPPER_BOOTS.get()) : "model is null");
//blocks
        blockModels.createTrivialCube(QuietusBlocks.EXAMPLE_BLOCK.get());

    }
    public void RegisterBow(@NonNull ItemModelGenerators itemModels, Item item, String location)
    {
        Identifier Identifier= BuiltInRegistries.ITEM.getKey(item);
        ItemModel.Unbaked itemmodel$unbaked = ItemModelUtils.plainModel(Identifier.withPrefix(location));
        ItemModel.Unbaked itemmodel$unbaked1 = ItemModelUtils.plainModel(Identifier.withSuffix("_pulling_0").withPrefix(location));
        ItemModel.Unbaked itemmodel$unbaked2 = ItemModelUtils.plainModel(Identifier.withSuffix("_pulling_1").withPrefix(location));
        ItemModel.Unbaked itemmodel$unbaked3 = ItemModelUtils.plainModel(Identifier.withSuffix("_pulling_2").withPrefix(location));
        itemModels.itemModelOutput.accept(
               item, ItemModelUtils.conditional(ItemModelUtils.isUsingItem(), ItemModelUtils.rangeSelect(new UseDuration(false), 0.05F, itemmodel$unbaked1, new RangeSelectItemModel.Entry[]{ItemModelUtils.override(itemmodel$unbaked2, 0.65F), ItemModelUtils.override(itemmodel$unbaked3, 0.9F)}), itemmodel$unbaked)
        );
    }

    @Override
    protected Stream<? extends Holder<Block>> getKnownBlocks() {
        return QuietusBlocks.BLOCKS.getEntries().stream();
    }

    @Override
    protected Stream<? extends Holder<Item>> getKnownItems() {
        return QuietusItems.REGISTRAR.getEntries().stream();
    }
}
